### ISSUE TITLE
Example of formal equivalence checking

### ISSUE THREAD

**Issue by jimmysitu** [YosysHQ/sby#129]
Hi, All

I notice SymbiYosys supports formal equivalence checking
Is there any example or doc about .sby file for equiv mode?

**Comment by nakengelhardt** [comment]
Hi Jimmy, there is not a 'proper' equivalence checking more in sby. Currently you have to create a miter circuit, which is possible to do semi-automatically in the `[script]` section of your sby config file by creating two `gold` and `gate` designs and then using the yosys command `miter`.

Yosys also has some limited equivalence checking capabilities which are used in some of the automated tests, e.g. https://github.com/YosysHQ/yosys/blob/master/tests/sat/clk2fflogic.ys. However this is more tricky to use, even less well documented than sby, and has some [known bugs](https://github.com/YosysHQ/yosys/issues/2728)...

We do have plans for a proper equivalence checking tool, but have unfortunately not been able to make progress on this due to lack of funding/more urgent priorites.
